# อบรมเรื่อง Python

In [1]:
print('abc')

abc


In [2]:
a = 10

In [3]:
a

10

In [4]:
print(a)

10


## ชนิดข้อมูล

In [5]:
type(a)

int

In [6]:
type(5.2)

float

In [7]:
type(True)

bool

In [8]:
type('abc')

str

In [9]:
a + 10

20

In [10]:
a - 5

5

In [11]:
a / 3

3.3333333333333335

In [12]:
a // 3

3

In [13]:
a % 3

1

In [14]:
a ** 2

100

In [15]:
a*2

20

In [16]:
b = 'สวัสดีครับ'

In [17]:
b

'สวัสดีครับ'

In [18]:
c = "ศรัณย์"

In [19]:
c

'ศรัณย์'

In [20]:
b + c

'สวัสดีครับศรัณย์'

In [21]:
b*3

'สวัสดีครับสวัสดีครับสวัสดีครับ'

In [22]:
b = 3

In [23]:
b*3

9

In [24]:
b

3

## Casting

In [25]:
c = 'ศรัณย์ อายุ = '

In [26]:
print(c + str(18))

ศรัณย์ อายุ = 18


In [27]:
b

3

In [28]:
str(b)

'3'

In [29]:
c = '15'

In [30]:
c

'15'

In [31]:
float(c)

15.0

In [32]:
bool(c)

True

In [33]:
bool(10)

True

In [34]:
bool(-2)

True

In [35]:
bool(0)

False

In [36]:
bool('')

False

In [37]:
bool('0')

True

## Collections
* List
* Tuple
* Dictionary
* Set

In [38]:
arr = [1, 20.5, 'abc']

In [39]:
arr

[1, 20.5, 'abc']

In [40]:
type(arr)

list

In [41]:
arr2 = list()

In [42]:
arr2

[]

In [43]:
type(arr2)

list

In [44]:
arr.append('ศรัณย์')

In [45]:
arr

[1, 20.5, 'abc', 'ศรัณย์']

## Indexing and Slicing

In [46]:
arr[0]

1

In [47]:
arr[1]

20.5

In [48]:
arr[2]

'abc'

In [49]:
arr[3]

'ศรัณย์'

In [50]:
arr[-1]

'ศรัณย์'

In [51]:
arr[-2]

'abc'

In [52]:
arr[-3]

20.5

In [53]:
arr[1:4]

[20.5, 'abc', 'ศรัณย์']

In [54]:
arr

[1, 20.5, 'abc', 'ศรัณย์']

In [55]:
arr[1:5]

[20.5, 'abc', 'ศรัณย์']

In [56]:
arr[1:]

[20.5, 'abc', 'ศรัณย์']

In [57]:
arr[:3]

[1, 20.5, 'abc']

In [58]:
arr

[1, 20.5, 'abc', 'ศรัณย์']

In [59]:
arr[::2]

[1, 'abc']

In [60]:
arr

[1, 20.5, 'abc', 'ศรัณย์']

In [61]:
arr[::-1]

['ศรัณย์', 'abc', 20.5, 1]

In [62]:
arr[0]

1

In [63]:
arr[0] = 10

In [64]:
arr

[10, 20.5, 'abc', 'ศรัณย์']

In [65]:
arr[1:3] = [2.5, 3.5]

In [66]:
arr

[10, 2.5, 3.5, 'ศรัณย์']

In [67]:
arr + arr

[10, 2.5, 3.5, 'ศรัณย์', 10, 2.5, 3.5, 'ศรัณย์']

## Tuple

In [68]:
t = (1, 5.2, 'abc')

In [69]:
t

(1, 5.2, 'abc')

In [70]:
type(t)

tuple

In [71]:
t2 = tuple()

In [72]:
type(t2)

tuple

In [73]:
t[0]

1

In [74]:
t[:2]

(1, 5.2)

In [75]:
t + t

(1, 5.2, 'abc', 1, 5.2, 'abc')

In [76]:
t

(1, 5.2, 'abc')

### Unpacking

In [77]:
x, y, z = t

In [78]:
x

1

In [79]:
y

5.2

In [80]:
z

'abc'

## Dictionary

In [81]:
d = {'a':12, 'b':15}

In [82]:
d

{'a': 12, 'b': 15}

In [83]:
d['a']

12

In [84]:
d['b']

15

In [85]:
d.keys()

dict_keys(['a', 'b'])

In [86]:
d.values()

dict_values([12, 15])

In [87]:
type(d)

dict

In [88]:
d2 = dict({'c':100, 20:'abc', 'a':10.2})

In [89]:
type(d2)

dict

In [90]:
d2

{'c': 100, 20: 'abc', 'a': 10.2}

In [91]:
d2['c']

100

In [92]:
d2[20]

'abc'

In [93]:
d2['a']

10.2

In [94]:
0.1+0.2

0.30000000000000004

In [95]:
d2.items()

dict_items([('c', 100), (20, 'abc'), ('a', 10.2)])

In [96]:
arr

[10, 2.5, 3.5, 'ศรัณย์']

In [97]:
10 in arr 

True

In [98]:
11 in arr

False

In [99]:
t

(1, 5.2, 'abc')

In [100]:
1 in t

True

In [101]:
2 in t

False

In [102]:
d

{'a': 12, 'b': 15}

In [103]:
'a' in d

True

In [104]:
12 in d.values()

True

## Control Flows
1. If-else statement
2. While loop
3. For loop

In [105]:
a = 10

In [106]:
if a == 10 or a == 20:
    print('a = 10, 20')
elif a == 5:
    print('a = 5')
else:
    print('not equal 5, 10, 20')
print('done')

a = 10, 20
done


In [107]:
i = 0
while i < 3:
    print(i)
    i = i+1
print('done')

0
1
2
done


## For loop

In [108]:
for i in range(5):
    print(i)

0
1
2
3
4


In [109]:
list(range(5))

[0, 1, 2, 3, 4]

In [110]:
arr

[10, 2.5, 3.5, 'ศรัณย์']

In [111]:
for i in arr:
    print(i)

10
2.5
3.5
ศรัณย์


In [112]:
for i in t:
    print(i)

1
5.2
abc


In [113]:
t

(1, 5.2, 'abc')

In [114]:
for i in d:
    print(i)

a
b


In [115]:
d.items()

dict_items([('a', 12), ('b', 15)])

In [116]:
for k, v in d.items():
    print(k, v)

a 12
b 15


## Function

In [117]:
def func():
    print('a')
    print('b')

In [118]:
func()

a
b


In [119]:
def f1(a, b, c):
    print(a + b + c)

In [120]:
f1(1,2,3)

6


In [121]:
def f2(a, b=2, c=3):
    print(a+b+c)

In [122]:
f2(1, 10)

14


In [123]:
f2(1, c=10)

13


In [124]:
def f3(a, b, c=3):
    return c, b, a

In [125]:
x, y, z = f3(2,1)

In [126]:
x

3

In [127]:
y

1

In [128]:
z

2

In [129]:
sum([1,2,3])

6

In [130]:
max([1,2,3])

3

In [131]:
min([1,2,3])

1

In [132]:
f = sum

In [133]:
f = min

In [134]:
f([1,2,3])

1

In [135]:
def f4(arr, f):
    return f(arr)

In [136]:
f4([1,2,3], sum)

6

In [137]:
f4([1,2,3], max)

3

In [138]:
f4([1,2,3], min)

1

In [139]:
def f5(a):
    def f6(b):
        return b ** a
    return f6

In [140]:
sq = f5(2)

In [141]:
sq

<function __main__.f5.<locals>.f6(b)>

In [142]:
sq(3)

9

In [143]:
sq(4)

16

In [144]:
cube = f5(3)

In [145]:
cube(3)

27

In [146]:
cube(4)

64

In [147]:
def fibbon():
    a = 1
    b = 1
    while True:
        c = a+b
        a = b
        b = c
        yield c

In [148]:
for i in fibbon():
    print(i)
    if i > 100:
        break

2
3
5
8
13
21
34
55
89
144


In [149]:
x = fibbon()

In [150]:
next(x)

2

In [151]:
f5

<function __main__.f5(a)>

In [152]:
def f7(a, b, c):
    return a+b+c

In [153]:
arr = [6,7,8]

In [154]:
f7(*arr)

21

In [155]:
def f8(*a):
    print(a)
    print(type(a))

In [156]:
f8(1,5,8,3,5)

(1, 5, 8, 3, 5)
<class 'tuple'>


In [157]:
f8(8.6,3,'abc')

(8.6, 3, 'abc')
<class 'tuple'>


In [158]:
def f9(a, b):
    return a/b

In [159]:
d = {'b':12, 'a':15}
d

{'b': 12, 'a': 15}

In [160]:
f9(**d)

1.25

In [161]:
def f10(**p):
    print(p)
    return p['a']/p['b']

In [162]:
f10(a=1,b=2,c=3)

{'a': 1, 'b': 2, 'c': 3}


0.5

## Module
1. Built-in
2. Customized
3. External

In [163]:
import os

In [164]:
os.getcwd()

'C:\\Users\\HP\\Desktop\\python_ws'

In [165]:
os.listdir('.')

['.ipynb_checkpoints',
 'sarun.py',
 'tu',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 '__pycache__']

In [166]:
os.path.join('..', 'HP', 'Sa run')

'..\\HP\\Sa run'

In [167]:
from os import path

In [168]:
path.join('.','HP')

'.\\HP'

In [169]:
from os.path import join

In [170]:
join('.','HP')

'.\\HP'

In [171]:
from datetime import datetime as d

In [172]:
d.now()

datetime.datetime(2020, 4, 16, 14, 57, 42, 98811)

In [173]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 5E94-F0AD

 Directory of C:\Users\HP\Desktop\python_ws

04/16/2020  02:53 PM    <DIR>          .
04/16/2020  02:53 PM    <DIR>          ..
04/16/2020  10:36 AM    <DIR>          .ipynb_checkpoints
04/16/2020  02:15 PM                59 sarun.py
04/16/2020  02:29 PM    <DIR>          tu
04/16/2020  02:53 PM            53,096 Untitled.ipynb
04/16/2020  10:48 AM             1,364 Untitled1.ipynb
04/16/2020  02:18 PM    <DIR>          __pycache__
               3 File(s)         54,519 bytes
               5 Dir(s)  125,886,017,536 bytes free


In [174]:
import sarun as s

In [175]:
s.func(2)

Hello
2


4

In [176]:
import tu.sci

In [177]:
tu.sci.func1()

TU Sci


In [178]:
import tu

In [179]:
import numpy 

In [180]:
import pandas

In [184]:
import xgboost

In [ ]:
!python -m pip install xgboost

## NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [7]:
a*2

array([2, 4, 6])

In [8]:
a.dtype

dtype('int32')

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
b = [1,6,9,10]
np.linspace(min(b),max(b),4)

array([ 1.,  4.,  7., 10.])

In [19]:
a

array([1, 2, 3])

In [18]:
a.ndim

1

In [20]:
c = np.zeros((2,3,4))

In [21]:
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
c.ndim

3

In [23]:
c.shape

(2, 3, 4)

In [24]:
d = np.array([1,2,3,4,5,6])

In [25]:
d.shape

(6,)

In [30]:
e = d.reshape(3,2)

In [31]:
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
e[0]

array([1, 2])

In [35]:
e[:,0]

array([1, 3, 5])

In [38]:
e[:2,0]

array([1, 3])

In [41]:
e[:,1:]

array([[2],
       [4],
       [6]])

In [42]:
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
f = np.array([10, 5])

In [50]:
e+f

array([[11,  7],
       [13,  9],
       [15, 11]])

In [48]:
e.shape

(3, 2)

In [49]:
f.shape

(2,)

In [52]:
e[:,0] + f

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [55]:
e[:,0].shape

(3,)

In [56]:
e[:,:1]

array([[1],
       [3],
       [5]])

In [57]:
f

array([10,  5])

In [53]:
e[:,:1] + f

array([[11,  6],
       [13,  8],
       [15, 10]])

In [58]:
e[:,:1]

array([[1],
       [3],
       [5]])

In [60]:
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
g = np.array([10, 5, 2])
g

array([10,  5,  2])

In [63]:
g.shape

(3,)

In [67]:
g[:,np.newaxis].shape

(3, 1)

In [66]:
e*g[:,np.newaxis]

array([[10, 20],
       [15, 20],
       [10, 12]])

## Pandas

In [68]:
import pandas as pd

In [76]:
df = pd.DataFrame(e, columns=['B', 'A'])

In [82]:
df.columns

Index(['B', 'A'], dtype='object')

In [83]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [85]:
df[['A', 'B', 'A']]

A  B  A
0  2  1  2
1  4  3  4
2  6  5  6

In [88]:
df[:2]

B  A
0  1  2
1  3  4

In [92]:
df.iloc[:2,0]

0    1
1    3
Name: B, dtype: int32

In [77]:
df

B  A
0  1  2
1  3  4
2  5  6

In [78]:
df.values

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
c.shape

(2, 3, 4)

## Open/Close File in Python

In [111]:
f = open('a.txt', 'r', encoding='utf-8')

In [112]:
f

<_io.TextIOWrapper name='a.txt' mode='r' encoding='utf-8'>

In [113]:
txt = f.read()

In [114]:
txt

'สวัสดี abc123'

In [115]:
f.close()

In [110]:
with open('a.txt', 'r', encoding='utf-8') as f:
    txt = f.read()
print(txt)

สวัสดี abc123
